version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/bcraft
    ports:
      - 8000:8000
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_USER=bcraft
      - POSTGRES_PASSWORD=bcraft
      - POSTGRES_DB=bcraft
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=bcraft
      - POSTGRES_PASSWORD=bcraft
      - POSTGRES_DB=bcraft
    ports:
      - 5432:5432

volumes:
  postgres_data: